import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js";
import { getAuth, signOut } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js";
import { getFirestore, collection, query, onSnapshot, doc, setDoc, updateDoc, addDoc, serverTimestamp, orderBy, where, getDocs, limit, arrayUnion } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-storage.js";

const firebaseConfig = {
  apiKey: "AIzaSyBtDMYBR0jcyK-JfgsYtET1SenPngzmQi4",
  authDomain: "mwamini-chatting-web.firebaseapp.com",
  databaseURL: "https://mwamini-chatting-web-default-rtdb.firebaseio.com",
  projectId: "mwamini-chatting-web",
  storageBucket: "mwamini-chatting-web.firebasestorage.app",
  messagingSenderId: "640958885512",
  appId: "1:640958885512:web:2f9a636acc85534009b93d",
  measurementId: "G-SW9FBXX78G"
};

const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

let currentUser = null; 
let activeChatId = null;
let selectedChatObject = null; 
let unsubscribeMessages = null;
let activeSessionStartTime = null; 

let audioMediaRecorder = null;
let recordedAudioChunks = [];
const trackedUnreadNotificationSet = new Set();

function initDashboardPage() {
    if (!document.getElementById("users-container") && !document.getElementById("message-form")) {
        return; 
    }

    const savedUid = localStorage.getItem("session_uid");
    const savedName = localStorage.getItem("session_name");

    if (!savedUid) {
        window.location.href = "index.html";
        return; 
    }

    currentUser = { uid: savedUid, name: savedName, accountMode: "standard" };
    updateDoc(doc(db, "users", currentUser.uid), { isOnline: true }).catch(() => {});

    onSnapshot(doc(db, "users", currentUser.uid), (docSnap) => {
        if (docSnap.exists()) {
            const data = docSnap.data();
            if(document.getElementById("current-user-title")) document.getElementById("current-user-title").innerText = data.name;
            if(document.getElementById("my-status-display")) document.getElementById("my-status-display").innerText = data.status || "Available";
        }
    });

    populateUtilityUsersDropdown();

    const backgroundSelector = document.getElementById("background-changer");
    if (backgroundSelector) {
        backgroundSelector.addEventListener("change", (e) => {
            const chosenColorHex = e.target.value;
            const messageLayoutCanvas = document.getElementById("message-stream");
            if (messageLayoutCanvas) {
                messageLayoutCanvas.style.backgroundColor = chosenColorHex;
                messageLayoutCanvas.style.color = (chosenColorHex === "#121b22") ? "#ffffff" : "#000000";
            }
        });
    }

    // --- INSTANT GROUP CREATION (TRACKS MEMBERS ARRAY UPON PROVISIONING) ---
    const groupSelectMenu = document.getElementById("group-type-select");
    const groupPasswordField = document.getElementById("group-password-input");
    const createGroupActionBtn = document.getElementById("create-group-btn");

    if (groupSelectMenu && groupPasswordField) {
        groupSelectMenu.addEventListener("change", (e) => {
            if (e.target.value === "protected") {
                groupPasswordField.classList.remove("hidden");
            } else {
                groupPasswordField.classList.add("hidden");
            }
        });
    }

    if (createGroupActionBtn) {
        createGroupActionBtn.addEventListener("click", async () => {
            const groupNameInput = document.getElementById("group-name-input");
            const title = groupNameInput ? groupNameInput.value.trim() : "";
            const architectureType = groupSelectMenu ? groupSelectMenu.value : "public";
            const codeKeyPayload = groupPasswordField ? groupPasswordField.value.trim() : "";

            if (!title) {
                alert("Please declare an assignment name label for your room.");
                return;
            }
            if (architectureType === "protected" && !codeKeyPayload) {
                alert("Protected channels require a password validation token asset.");
                return;
            }

            try {
                const autoGeneratedRoomKey = "ROOM_" + Date.now();
                await setDoc(doc(db, "users", autoGeneratedRoomKey), {
                    uid: autoGeneratedRoomKey,
                    name: `[ROOM] ${title}`,
                    status: `Open Global Channel (${architectureType.toUpperCase()})`,
                    isGroup: true,
                    groupType: architectureType,
                    groupPassword: codeKeyPayload,
                    isOnline: true,
                    allowedMembers: [currentUser.uid] // Creator initialized automatically
                });

                alert(`Global Chat Room "${title}" created successfully!`);
                if(groupNameInput) groupNameInput.value = "";
                if(groupPasswordField) groupPasswordField.value = "";
                executeTargetSearchQuery(""); 
            } catch (err) {
                alert("Room composition failure: " + err.message);
            }
        });
    }

    // --- UPGRADED CONTEXTUAL MEMBER ADDITION INTERFACE ROUTINE ---
    const addMemberActionBtn = document.getElementById("btn-add-member-action");
    if (addMemberActionBtn) {
        addMemberActionBtn.addEventListener("click", async () => {
            const selectMenu = document.getElementById("utility-member-dropdown");
            if (!selectMenu || !selectMenu.value || !activeChatId) return;
            
            const targetedUserUid = selectMenu.value;
            const targetedUserName = selectMenu.options[selectMenu.selectedIndex].text;

            try {
                // Provision permissions natively directly inside the user's room document state
                await updateDoc(doc(db, "users", activeChatId), {
                    allowedMembers: arrayUnion(targetedUserUid)
                });

                await addDoc(collection(db, "chats", activeChatId, "messages"), {
                    text: `📢 Google Assistant Alert: ${targetedUserName} has been granted verified clearance to participate inside this chatroom.`,
                    type: "text",
                    senderId: "SYSTEM_UPGRADE",
                    senderName: "Google Assistant Hub",
                    createdAt: serverTimestamp()
                });
                alert(`Clearance granted successfully! ${targetedUserName} is now a participant.`);
            } catch (err) {
                alert("Failed to append room permission structural state: " + err.message);
            }
        });
    }

    const generateInviteBtn = document.getElementById("btn-generate-invite");
    if (generateInviteBtn) {
        generateInviteBtn.addEventListener("click", () => {
            if (!activeChatId || !selectedChatObject) return;
            const displayBox = document.getElementById("invite-link-display");
            if (!displayBox) return;

            let inviteStringPayload = `${window.location.origin}/dashboard.html?joinRoomId=${activeChatId}`;
            if (selectedChatObject.groupType === "protected") {
                inviteStringPayload += `&token=${btoa(selectedChatObject.groupPassword)}`;
            }

            displayBox.innerText = inviteStringPayload;
            displayBox.classList.remove("hidden");
            alert("Invite link copied below. Users clicking this link automatically get added to the room list.");
        });
    }

    // --- AUTOMATIC INBOUND LINK DETECTOR PASSTHROUGH ENGINE ---
    const urlParams = new URLSearchParams(window.location.search);
    const incomingRoomId = urlParams.get('joinRoomId');
    if (incomingRoomId) {
        setTimeout(async () => {
            try {
                await updateDoc(doc(db, "users", incomingRoomId), {
                    allowedMembers: arrayUnion(currentUser.uid)
                });
                window.history.replaceState({}, document.title, window.location.pathname);
                alert("Successfully joined chatroom via secure link invitation!");
                executeTargetSearchQuery("");
            } catch(e) {}
        }, 1500);
    }

    // --- UNREAD TRAFFIC ALERT PIPELINE ---
    onSnapshot(collection(db, "chats"), (snapshot) => {
        snapshot.forEach((chatDoc) => {
            const info = chatDoc.data();
            if (chatDoc.id.startsWith("ROOM_") || (info.participants && info.participants.includes(currentUser.uid))) {
                onSnapshot(query(collection(db, "chats", chatDoc.id, "messages"), orderBy("createdAt", "desc"), limit(1)), (lastMessageSnapshot) => {
                    lastMessageSnapshot.forEach((mDoc) => {
                        const packet = mDoc.data();
                        if (packet.senderId !== currentUser.uid && chatDoc.id !== activeChatId) {
                            trackedUnreadNotificationSet.add(chatDoc.id);
                            renderSidebarUnreadAlertBadge(chatDoc.id);
                        }
                    });
                });
            }
        });
    });

    // --- VOICE MEMO CAPTURE MECHANIC ---
    const recordVoiceBtn = document.getElementById("voice-record-btn");
    const recordStatusText = document.getElementById("voice-recording-status");

    if (recordVoiceBtn) {
        recordVoiceBtn.addEventListener("click", async () => {
            if (!activeChatId) return;
            if (!audioMediaRecorder) {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
                    audioMediaRecorder = new MediaRecorder(stream);
                    audioMediaRecorder.ondataavailable = (e) => { if (e.data.size > 0) recordedAudioChunks.push(e.data); };
                    audioMediaRecorder.onstop = async () => {
                        const audioBlob = new Blob(recordedAudioChunks, { type: "audio/ogg; codecs=opus" });
                        recordedAudioChunks = [];
                        if(recordStatusText) recordStatusText.classList.add("hidden");
                        recordVoiceBtn.style.color = "initial";

                        const voiceStorageRef = ref(storage, `voice_memos/${activeChatId}/${Date.now()}_clip.ogg`);
                        const snap = await uploadBytes(voiceStorageRef, audioBlob);
                        const downloadUrl = await getDownloadURL(snap.ref);

                        await addDoc(collection(db, "chats", activeChatId, "messages"), {
                            text: "Voice Note Transmission",
                            fileUrl: downloadUrl,
                            type: "audio",
                            senderId: currentUser.uid,
                            senderName: currentUser.name,
                            createdAt: serverTimestamp()
                        });
                    };
                } catch (err) {
                    alert("Audio device access denied: " + err.message);
                    return;
                }
            }

            if (audioMediaRecorder.state === "inactive") {
                audioMediaRecorder.start();
                if(recordStatusText) recordStatusText.classList.remove("hidden");
                recordVoiceBtn.style.color = "#ea0038";
            } else {
                audioMediaRecorder.stop();
            }
        });
    }

    const searchField = document.getElementById("search-users");
    if (searchField) {
        searchField.addEventListener("input", (e) => executeTargetSearchQuery(e.target.value.trim()));
    }
    executeTargetSearchQuery(""); 

    const messageForm = document.getElementById("message-form");
    if (messageForm) {
        messageForm.addEventListener("submit", async (e) => {
            e.preventDefault();
            const input = document.getElementById("message-input");
            if (!input || !input.value.trim() || !activeChatId) return;

            const text = input.value.trim();
            input.value = "";

            await addDoc(collection(db, "chats", activeChatId, "messages"), {
                text: text,
                type: "text",
                senderId: currentUser.uid,
                senderName: currentUser.name,
                createdAt: serverTimestamp()
            });
        });
    }

    const logoutBtn = document.getElementById("logout-btn");
    if (logoutBtn) {
        logoutBtn.addEventListener("click", async () => {
            await updateDoc(doc(db, "users", currentUser.uid), { isOnline: false }).catch(() => {});
            localStorage.clear();
            signOut(auth).finally(() => { window.location.href = "index.html"; });
        });
    }
}

async function populateUtilityUsersDropdown() {
    const dropdownMenu = document.getElementById("utility-member-dropdown");
    if (!dropdownMenu) return;
    
    onSnapshot(query(collection(db, "users")), (snapshot) => {
        dropdownMenu.innerHTML = `<option value="">-- Choose Workspace Profile --</option>`;
        snapshot.forEach((userDoc) => {
            const info = userDoc.data();
            if (!info.isGroup && info.uid !== currentUser.uid) {
                const opt = document.createElement("option");
                opt.value = info.uid;
                opt.innerText = info.name;
                dropdownMenu.appendChild(opt);
            }
        });
    });
}

let groupUnsubscribeInstance = null;

async function executeTargetSearchQuery(keyword) {
    const listCanvas = document.getElementById("users-container");
    if (!listCanvas) return;
    listCanvas.innerHTML = "";

    if (groupUnsubscribeInstance) {
        groupUnsubscribeInstance();
        groupUnsubscribeInstance = null;
    }

    if (!keyword) {
        groupUnsubscribeInstance = onSnapshot(query(collection(db, "users")), (snapshot) => {
            listCanvas.innerHTML = ""; 
            if (snapshot.empty) return;
            
            snapshot.forEach((doc) => {
                const item = doc.data();
                if(item.isGroup) buildSidebarChannelRowElement(item);
            });
            snapshot.forEach((doc) => {
                const item = doc.data();
                if(!item.isGroup && item.uid !== currentUser.uid) buildSidebarChannelRowElement(item);
            });
        });
        return;
    }

    const standardKeywordSnap = await getDocs(query(collection(db, "users"), where("name", "==", keyword)));
    standardKeywordSnap.forEach((userDoc) => {
        const data = userDoc.data();
        if (data.uid !== currentUser.uid) {
            buildSidebarChannelRowElement(data);
        }
    });
}

function buildSidebarChannelRowElement(userData) {
    const canvas = document.getElementById("users-container");
    let rowElement = document.getElementById(`sidebar-row-${userData.uid}`);
    if (!rowElement) {
        rowElement = document.createElement("div");
        rowElement.id = `sidebar-row-${userData.uid}`;
        if(canvas) canvas.appendChild(rowElement);
    }
    
    rowElement.style = "display:flex; align-items:center; justify-content:space-between; padding:12px 16px; cursor:pointer; border-bottom:1px solid #f8f9fa; transition: background 0.1s;";
    rowElement.onmouseenter = () => rowElement.style.backgroundColor = "#f0f2f5";
    rowElement.onmouseleave = () => rowElement.style.backgroundColor = "transparent";

    const isRoomChannel = userData.isGroup === true;
    let badgeClass = userData.isOnline ? "status-online" : "status-offline";
    let statusTextLabel = userData.isOnline ? "online" : "offline";

    if (isRoomChannel) {
        badgeClass = (userData.groupType === "protected") ? "status-protected" : "status-public";
        statusTextLabel = (userData.groupType === "protected") ? "🔒 Protected" : "🌐 Public";
    }

    rowElement.innerHTML = `
        <div style="display:flex; align-items:center; gap:12px; flex:1; min-width:0;">
            <div style="background:${isRoomChannel ? '#008069' : '#00a884'}; color:white; width:44px; height:44px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:18px; flex-shrink:0;">
                ${isRoomChannel ? '👥' : userData.name.charAt(0).toUpperCase()}
            </div>
            <div style="flex:1; min-width:0;">
                <h4 style="margin:0; font-size:14px; color:#111b21; font-weight:600; display:flex; align-items:center;">
                    <span style="white-space:nowrap; overflow:hidden; text-overflow:ellipsis; max-width:150px;">${userData.name}</span>
                    <span class="status-badge ${badgeClass}">${statusTextLabel}</span>
                </h4>
                <p style="margin:2px 0 0 0; font-size:12px; color:#667781; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">${userData.status || 'Available'}</p>
            </div>
        </div>
        <div id="badge-holder-${userData.uid}" style="flex-shrink:0; padding-left:10px;"></div>
    `;

    const newRowElement = rowElement.cloneNode(true);
    if(rowElement.parentNode) rowElement.parentNode.replaceChild(newRowElement, rowElement);

    newRowElement.addEventListener("click", () => {
        if (isRoomChannel && userData.groupType === "protected") {
            const membersList = userData.allowedMembers || [];
            // If the current user isn't directly cleared inside the room array, trigger password gate check
            if (!membersList.includes(currentUser.uid)) {
                const clientAttemptToken = prompt(`Security Verification required.\nEnter password to access "${userData.name}":`);
                if (clientAttemptToken !== userData.groupPassword) {
                    alert("Authorization Denied: Invalid password key.");
                    return;
                }
                // Save access natively to allow them instant entry on subsequent visits
                updateDoc(doc(db, "users", userData.uid), {
                    allowedMembers: arrayUnion(currentUser.uid)
                }).catch(() => {});
            }
        }

        activeChatId = userData.uid;
        selectedChatObject = userData; 
        activeSessionStartTime = new Date();

        trackedUnreadNotificationSet.delete(activeChatId);
        const dynamicAlertWidgetRef = document.getElementById(`badge-holder-${userData.uid}`);
        if(dynamicAlertWidgetRef) dynamicAlertWidgetRef.innerHTML = "";

        document.getElementById("no-chat-selected").classList.add("hidden");
        document.getElementById("active-chat-area").classList.remove("hidden");
        
        // POPULATE METADATA STRINGS DIRECTLY ABOVE CHATROOM NAME DISPLAY
        const metaField = document.getElementById("chat-header-group-meta");
        if(metaField) {
            metaField.innerText = isRoomChannel 
              ? `ROOM METADATA INFO // ACCESS: ${userData.groupType.toUpperCase()} MODE` 
              : "DIRECT PRIVATE CONVERSATION";
        }

        document.getElementById("chat-header-name").innerText = userData.name;

        const presenceBadge = document.getElementById("chat-header-presence-badge");
        if(presenceBadge) {
            presenceBadge.className = `status-badge ${badgeClass}`;
            presenceBadge.innerText = statusTextLabel;
        }

        const utilitiesSidebar = document.getElementById("group-utilities-sidebar");
        if (utilitiesSidebar) {
            if (isRoomChannel) {
                utilitiesSidebar.classList.remove("hidden");
                const displayBox = document.getElementById("invite-link-display");
                if (displayBox) displayBox.classList.add("hidden"); 
            } else {
                utilitiesSidebar.classList.add("hidden");
            }
        }

        setDoc(doc(db, "chats", activeChatId), {
            chatId: activeChatId,
            participants: isRoomChannel ? [currentUser.uid] : [currentUser.uid, userData.uid],
            updatedAt: serverTimestamp()
        }, { merge: true });

        bindLiveIsolatedMessageStreams(collection(db, "chats", activeChatId, "messages"));
    });

    if (trackedUnreadNotificationSet.has(userData.uid)) {
        renderSidebarUnreadAlertBadge(userData.uid);
    }
}

function renderSidebarUnreadAlertBadge(targetKeyId) {
    const targetElementRef = document.getElementById(`badge-holder-${targetKeyId}`);
    if (targetElementRef) {
        targetElementRef.innerHTML = `<span class="unread-indicator">NEW</span>`;
    }
}

function bindLiveIsolatedMessageStreams(collectionReference) {
    if (unsubscribeMessages) unsubscribeMessages();
    unsubscribeMessages = onSnapshot(query(collectionReference, orderBy("createdAt", "asc")), (snapshot) => {
        const chatBoxWindow = document.getElementById("message-stream");
        if (!chatBoxWindow) return;
        chatBoxWindow.innerHTML = "";

        snapshot.forEach((msgDoc) => {
            const data = msgDoc.data();
            if (!data.createdAt) return;

            if (data.createdAt.toDate() >= activeSessionStartTime) {
                const bubbleRow = document.createElement("div");
                const isMe = data.senderId === currentUser.uid;
                bubbleRow.style = `display:flex; justify-content:${isMe ? 'flex-end' : 'flex-start'}; margin-bottom:12px;`;
                
                let visualPayloadOutputBlock = "";
                if (data.type === "audio") {
                    visualPayloadOutputBlock = `<audio src="${data.fileUrl}" controls style="max-width:250px; outline:none;"></audio>`;
                } else {
                    visualPayloadOutputBlock = `
                        <div style="display:flex; justify-content:space-between; align-items:center; gap:25px; margin-bottom:3px;">
                            <span style="font-size:11px; font-weight:bold; color:#008069;">${data.senderName}</span>
                            <span class="read-aloud-bot" style="cursor:pointer; font-size:11px; font-weight:600; color:#00a884; background:rgba(0,168,132,0.08); padding:1px 5px; border-radius:4px;" title="Ask Google Assistant to Read">✨ Google Assistant</span>
                        </div>
                        <p style="margin:0; font-size:14px; white-space:pre-wrap; line-height:1.5; color:#111b21;">${data.text}</p>
                    `;
                }

                bubbleRow.innerHTML = `<div style="background:${isMe ? '#d9fdd3' : '#ffffff'}; padding:9px 14px; border-radius:10px; box-shadow:0 1px 2px rgba(0,0,0,0.06); max-width:68%; word-wrap:break-word;">${visualPayloadOutputBlock}</div>`;
                
                const cloudSpeakerBtn = bubbleRow.querySelector(".read-aloud-bot");
                if(cloudSpeakerBtn) {
                    cloudSpeakerBtn.addEventListener("click", () => {
                        const narrativeInstance = new SpeechSynthesisUtterance(data.text);
                        
                        // Select Google Voice synthesizers inside standard Web Speech controllers
                        const platformAvailableVoices = window.speechSynthesis.getVoices();
                        const googleVoiceAsset = platformAvailableVoices.find(v => v.name.includes("Google") || v.name.includes("Assistant"));
                        if(googleVoiceAsset) {
                            narrativeInstance.voice = googleVoiceAsset;
                        }
                        
                        narrativeInstance.lang = 'en-US';
                        window.speechSynthesis.speak(narrativeInstance);
                    });
                }

                chatBoxWindow.appendChild(bubbleRow);
            }
        });
        chatBoxWindow.scrollTop = chatBoxWindow.scrollHeight;
    });
}

if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initDashboardPage);
} else {
    initDashboardPage();
}
